### ISSUE TITLE
Stripped binaries

### ISSUE THREAD

**Issue by alexjurkiewicz** [draeath/crawl-web-container#1]
Nice work building this container. It would be nice for public server operators if they could run each process in a container like this, to reduce the attack surface if attackers can break out of the DCSS binary.

I wanted to note the Dockerfile line `RUN strip --strip-unneeded crawl` will make crashlogs useless for debugging. For public servers, Crawl devs like unstripped binaries so crashlogs are informative 🙏

**Comment by draeath** [comment]
Thanks, fair point. That was put in more by habit than anything else.

**Comment by draeath** [comment]
@alexjurkiewicz you might find it interesting that the Makefile emits a stripped binary as-is if you build it like so:

    make -j$(nproc) prefix=/usr/local NO_TRY_LLD=y LTO=y TILES=y
    sudo make -j$(nproc) prefix=/usr/local NO_TRY_LLD=y LTO=y TILES=y install install-xdg-data

So while there was really no reason for me to be calling strip, the debug symbols are already getting removed in a normal build. (the above build commands are what I was doing for local builds before looking into webtiles)

**Comment by alexjurkiewicz** [comment]
You're totally right, I forgot you have to specify a no-op `strip` binary like `STRIP=true`. Don't remember if this should go before (eg as env `STRIP=true make ...`), after (`make STRIP=true ...`), or if it makes no difference.

**Comment by draeath** [comment]
I'm not sure if it works as an environment variable, but as a make argument it does. This leaves the binary unstripped on my host:

    make -j$(nproc) prefix=/usr/local NO_TRY_LLD=y LTO=y TILES=y STRIP=/bin/true
    file crawl
    crawl: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=f83c3d738e2bea2e9561beef7e231c079f33711a, for GNU/Linux 3.2.0, with debug_info, not stripped

The difference in size is (for `origin/stone_soup-0.32` on my host) 18M stripped, 30M unstripped, which isn't really that large of a difference (relative to your typical cache sizes, to say nothing of the libraries linked in at runtime). I'm going to explicitly disable strip in this container.
